site_name: Metro Stad - APV
site_url: https://exqlusive.github.io/metro-stad-apv/
theme:
  name: material
  use_directory_urls: false
  font:
    text: Rubik
  logo: assets/main_inverted.png
  favicon: assets/main_inverted.png
  features:
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - pymdownx.critic
  language: nl
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Verander naar donkere modus
      primary: deep purple
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Verander naar lichte modus
      primary: deep purple
      accent: blue
markdown_extensions:
  - attr_list
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
copyright: |
  &copy; 2024 Metro Stad
nav:
  - Hoofdpagina: index.md
  - Algemene Plaatselijke Verordening (APV): apv.md
  - Politie Wetboek: politie_wetboek.md
  - Risico Gebieden: risico_gebieden.md
  - Douane Gebieden: douane_gebieden.md
  - No Fly Zones: no_fly_zones.md
  - Belastingen: belastingen.md
  - Streamen: streamen.md