site_name: Metro Stad - APV
#site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  use_directory_urls: false
  font:
    text: Poppins
  logo: assets/main_inverted.png
  favicon: assets/main_inverted.png
  features:
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: nl
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Verander naar donkere modus
      primary: deep purple
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Verander naar lichte modus
      primary: deep purple
      accent: blue

copyright: |
  &copy; 2024 Metro Stad
  
nav:
  - Hoofdpagina: index.md
  - Algemene Plaatselijke Verordening (APV): apv.md
  - Politie Wetboek: politie_wetboek.md
  - Risico Gebieden: risico_gebieden.md
  - Douane Gebieden: douane_gebieden.md
  - No Fly Zones: no_fly_zones.md
  - Belastingen: belastingen.md
  - Streamen: streamen.md